### ISSUE TITLE
connecting to a hidden network?

### ISSUE THREAD

**Issue by panosnethood** [mazi-project/admin#1]
Hi, I would like to connect my Raspberry Pi to a hidden local network for Internet access. Would this be possible? In the worst case, I could do this through the terminal ...

**Comment by haniavis** [comment]
Hi Panos, this issue should probably go to the [portal ](https://github.com/mazi-project/portal) repository.

This one is the old admin interface.

I am closing this.

**Comment by panosnethood** [comment]
Perhaps to remove this repository completely to avoid confusion @haniavis ?
